import { Metadata } from "next"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { ShieldCheck } from "lucide-react"

export const metadata: Metadata = {
  title: "Privacy Policy | BitBasis",
  description: "Learn how BitBasis protects your data and privacy",
}

export default function PrivacyPage() {
  return (
    <div className="flex min-h-screen flex-col text-gray-300 overflow-x-hidden relative isolate">
      {/* Global Background Gradient & Grid */}
      <div 
        className="fixed inset-0 z-[-2] bg-gradient-to-b from-[#0F1116] via-[#171923] to-[#13151D]"
      />
      <div 
        className="fixed inset-0 z-[-1] opacity-[0.07]"
        style={{
          backgroundImage: 'radial-gradient(circle, white 1px, transparent 1px)',
          backgroundSize: '30px 30px'
        }}
      />
      {/* Noise Texture Overlay */}
      <div 
        className="fixed inset-0 z-[-1] opacity-30 mix-blend-soft-light pointer-events-none"
        style={{ 
          backgroundImage: 'url(\'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 800"><defs><filter id="noiseFilter"><feTurbulence type="fractalNoise" baseFrequency="0.8" numOctaves="3" stitchTiles="stitch"/></filter></defs><rect width="100%" height="100%" filter="url(%23noiseFilter)"/></svg>\')',
        }} 
      />

      <div className="container mx-auto px-4 py-12 max-w-8xl relative z-10">
        <div className="flex items-center space-x-2 mb-8">
          <ShieldCheck className="h-7 w-7 text-bitcoin-orange" />
          <h1 className="text-3xl font-bold text-white">Privacy Policy</h1>
        </div>
        
        <div className="flex flex-col gap-6 bg-gray-800/20 rounded-xl p-8 backdrop-blur-sm">
          <p className="text-gray-400">Effective date: January 1, 2025</p>
          <p className="text-gray-400">Last updated: November 6, 2025</p>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-white">1. Introduction</h2>
            <p className="text-gray-400">
              Welcome to BitBasis.
            </p>
            <p className="text-gray-400">
              BitBasis (&quot;us&quot;, &quot;we&quot;, or &quot;our&quot;) operates https://bitbasis.io (hereinafter referred to as &quot;Service&quot;).
            </p>
            <p className="text-gray-400">
              Our Privacy Policy governs your visit to bitbasis.io and explains how we collect, safeguard and disclose information that results from your use of our Service.
            </p>
            <p className="text-gray-400">
              We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
            </p>
            <p className="text-gray-400">
              Our Terms and Conditions (&quot;Terms&quot;) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (&quot;Agreement&quot;).
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-white">2. Definitions</h2>
            <p className="text-gray-400">
              <span className="font-medium text-white">SERVICE</span> means the bitbasis.io website operated by BitBasis.
            </p>
            <p className="text-gray-400">
              <span className="font-medium text-white">PERSONAL DATA</span> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
            </p>
            <p className="text-gray-400">
              <span className="font-medium text-white">USAGE DATA</span> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).
            </p>
            <p className="text-gray-400">
              <span className="font-medium text-white">COOKIES</span> are small files stored on your device (computer or mobile device).
            </p>
            <p className="text-gray-400">
              <span className="font-medium text-white">DATA CONTROLLER</span> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.
            </p>
            <p className="text-gray-400">
              <span className="font-medium text-white">DATA PROCESSORS (OR SERVICE PROVIDERS)</span> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.
            </p>
            <p className="text-gray-400">
              <span className="font-medium text-white">DATA SUBJECT</span> is any living individual who is the subject of Personal Data.
            </p>
            <p className="text-gray-400">
              <span className="font-medium text-white">THE USER</span> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-white">3. Information Collection and Use</h2>
            <p className="text-gray-400">
              We collect several different types of information for various purposes to provide and improve our Service to you.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-white">4. Types of Data Collected</h2>
            
            <div className="space-y-3">
              <h3 className="text-lg font-medium text-white">Personal Data</h3>
              <p className="text-gray-400">
                While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (&quot;Personal Data&quot;). Personally identifiable information may include, but is not limited to:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-400">
                <li>Email address</li>
                <li>Bitcoin transaction data from CSV files you upload, including dates, amounts, prices, transaction types, and any notes you add</li>
              </ul>
            </div>

            <div className="space-y-3 mt-4">
              <h3 className="text-lg font-medium text-white">Usage Data</h3>
              <p className="text-gray-400">
                We may also collect information that your browser sends whenever you visit our Service (&quot;Usage Data&quot;).
              </p>
              <p className="text-gray-400">
                This Usage Data may include information such as your computer&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
              </p>
              <p className="text-gray-400">
                We use Vercel Analytics and Speed Insights to collect anonymous usage and performance data. This data is collected without cookies and uses daily hash resets to ensure users cannot be tracked across different days or websites. Currently, these analytics are active by default, though we plan to implement an opt-in mechanism in the future.
              </p>
            </div>

            <div className="space-y-3 mt-4">
              <h3 className="text-lg font-medium text-white">Terms Acceptance Data</h3>
              <p className="text-gray-400">
                When you accept our Terms of Service and Privacy Policy during account creation, we collect your IP address and user agent string. This information is used solely to maintain a record of your acceptance of our terms and is stored securely in our database.
              </p>
            </div>

            <div className="space-y-3 mt-4">
              <h3 className="text-lg font-medium text-white">Tracking Cookies Data</h3>
              <p className="text-gray-400">
                We use cookies and similar tracking technologies to track activity on our Service and we hold certain information.
              </p>
              <p className="text-gray-400">
                Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device.
              </p>
              <p className="text-gray-400">
                Examples of Cookies we use:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-400">
                <li><span className="font-medium text-white">Session Cookies:</span> We use Session Cookies to operate our Service for authentication purposes only. These are HTTP-only cookies that cannot be accessed by JavaScript.</li>
                <li><span className="font-medium text-white">Security Cookies:</span> We use Security Cookies for security purposes to maintain your authenticated session.</li>
              </ul>
              <p className="text-gray-400">
                You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
              </p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-white">5. Use of Data</h2>
            <p className="text-gray-400">
              BitBasis uses the collected data for various purposes:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-400">
              <li>to provide and maintain our Service</li>
              <li>to notify you about changes to our Service</li>
              <li>to allow you to participate in interactive features of our Service when you choose to do so</li>
              <li>to provide customer support</li>
              <li>to gather analysis or valuable information so that we can improve our Service</li>
              <li>to monitor the usage of our Service</li>
              <li>to detect, prevent and address technical issues</li>
              <li>to fulfill any other purpose for which you provide it</li>
              <li>to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection</li>
              <li>to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.</li>
              <li>in any other way we may describe when you provide the information</li>
              <li>for any other purpose with your consent</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-white">6. Retention of Data</h2>
            <p className="text-gray-400">
              We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
            </p>
            <p className="text-gray-400">
              We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
            </p>
            <p className="text-gray-400">
              You may request deletion of your account and all associated data at any time through your account settings or by contacting us at hello@bitbasis. Upon account deletion, we will remove your Personal Data and portfolio data from our systems, except where we are required to retain certain information for legal or regulatory purposes.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-white">7. Transfer of Data</h2>
            <p className="text-gray-400">
              Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
            </p>
            <p className="text-gray-400">
              If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there.
            </p>
            <p className="text-gray-400">
              Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
            </p>
            <p className="text-gray-400">
              BitBasis will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-white">8. Disclosure of Data</h2>
            <p className="text-gray-400">
              We may disclose personal information that we collect, or you provide:
            </p>
            
            <div className="space-y-3 mt-3">
              <h3 className="text-lg font-medium text-white">Disclosure for Law Enforcement</h3>
              <p className="text-gray-400">
                Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.
              </p>
            </div>

            <div className="space-y-3 mt-3">
              <h3 className="text-lg font-medium text-white">Business Transaction</h3>
              <p className="text-gray-400">
                If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.
              </p>
            </div>

            <div className="space-y-3 mt-3">
              <h3 className="text-lg font-medium text-white">Other cases</h3>
              <p className="text-gray-400">
                We may disclose your information also:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-400">
                <li>to contractors, service providers, and other third parties we use to support our business</li>
                <li>to fulfill the purpose for which you provide it</li>
                <li>for any other purpose disclosed by us when you provide the information</li>
                <li>with your consent in any other cases</li>
                <li>if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others</li>
              </ul>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-white">9. Security of Data</h2>
            <p className="text-gray-400">
              The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
            </p>
            <p className="text-gray-400">
              All data is stored in our secure Supabase database with the following protections:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-400">
              <li>Row-level security policies that ensure you can only access your own data</li>
              <li>Encrypted data transmission using HTTPS/TLS</li>
              <li>Secure authentication via Supabase Auth using magic link authentication (passwordless)</li>
              <li>HTTP-only cookies for session management</li>
              <li>Regular security audits and updates</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-white">10. Your Data Protection Rights Under General Data Protection Regulation (GDPR)</h2>
            <p className="text-gray-400">
              If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR. – See more at https://eur-lex.europa.eu/eli/reg/2016/679/oj
            </p>
            <p className="text-gray-400">
              We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
            </p>
            <p className="text-gray-400">
              If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at hello@bitbasis.
            </p>
            <p className="text-gray-400">
              In certain circumstances, you have the following data protection rights:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-400">
              <li><span className="font-medium text-white">The right to access, update or to delete the information we have on you.</span> You can access, update, or request deletion of your Personal Data directly from your account settings or by contacting us.</li>
              <li><span className="font-medium text-white">The right of rectification.</span> You have the right to have your information rectified if that information is inaccurate or incomplete.</li>
              <li><span className="font-medium text-white">The right to object.</span> You have the right to object to our processing of your Personal Data.</li>
              <li><span className="font-medium text-white">The right of restriction.</span> You have the right to request that we restrict the processing of your personal information.</li>
              <li><span className="font-medium text-white">The right to data portability.</span> You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format. You can export your transaction data as CSV from your account settings.</li>
              <li><span className="font-medium text-white">The right to withdraw consent.</span> You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information.</li>
            </ul>
            <p className="text-gray-400">
              Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.
            </p>
            <p className="text-gray-400">
              You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-white">11. Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)</h2>
            <p className="text-gray-400">
              CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law&apos;s reach stretches well beyond California to require a person or company in the United States (and conceivable the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy. – See more at: https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/
            </p>
            <p className="text-gray-400">
              According to CalOPPA we agree to the following:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-400">
              <li>users can visit our site anonymously</li>
              <li>our Privacy Policy link includes the word &quot;Privacy&quot;, and can easily be found on the page specified above on the home page of our website</li>
              <li>users will be notified of any privacy policy changes on our Privacy Policy Page</li>
              <li>users are able to change their personal information by emailing us at hello@bitbasis</li>
            </ul>
            <p className="text-gray-400">
              <span className="font-medium text-white">Our Policy on &quot;Do Not Track&quot; Signals:</span>
            </p>
            <p className="text-gray-400">
              We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.
            </p>
            <p className="text-gray-400">
              You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-white">12. Your Data Protection Rights under the California Consumer Privacy Act (CCPA)</h2>
            <p className="text-gray-400">
              If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:
            </p>
            
            <div className="space-y-3 mt-3">
              <h3 className="text-lg font-medium text-white">What personal information we have about you</h3>
              <p className="text-gray-400">
                If you make this request, we will return to you:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-400">
                <li>The categories of personal information we have collected about you.</li>
                <li>The categories of sources from which we collect your personal information.</li>
                <li>The business or commercial purpose for collecting or selling your personal information.</li>
                <li>The categories of third parties with whom we share personal information.</li>
                <li>The specific pieces of personal information we have collected about you.</li>
                <li>A list of categories of personal information that we have sold, along with the category of any other company we sold it to. If we have not sold your personal information, we will inform you of that fact.</li>
                <li>A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with.</li>
              </ul>
              <p className="text-gray-400">
                Please note, you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months.
              </p>
            </div>

            <div className="space-y-3 mt-3">
              <h3 className="text-lg font-medium text-white">To delete your personal information</h3>
              <p className="text-gray-400">
                If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.
              </p>
            </div>

            <div className="space-y-3 mt-3">
              <h3 className="text-lg font-medium text-white">To stop selling your personal information</h3>
              <p className="text-gray-400">
                We don&apos;t sell or rent your personal information to any third parties for any purpose. You are the only owner of your Personal Data and can request disclosure or deletion at any time.
              </p>
            </div>

            <p className="text-gray-400 mt-4">
              Please note, if you ask us to delete or stop selling your data, it may impact your experience with us, and you may not be able to participate in certain programs or membership services which require the usage of your personal information to function. But in no circumstances, we will discriminate against you for exercising your rights.
            </p>
            <p className="text-gray-400">
              To exercise your California data protection rights described above, please send your request(s) by one of the following means:
            </p>
            <p className="text-gray-400">
              By email: hello@bitbasis
            </p>
            <p className="text-gray-400">
              By visiting this page on our website: https://bitbasis.io/contact
            </p>
            <p className="text-gray-400">
              Your data protection rights, described above, are covered by the CCPA, short for the California Consumer Privacy Act. To find out more, visit the official California Legislative Information website. The CCPA took effect on 01/01/2020.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-white">13. Service Providers</h2>
            <p className="text-gray-400">
              We may employ third party companies and individuals to facilitate our Service (&quot;Service Providers&quot;), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.
            </p>
            <p className="text-gray-400">
              These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
            </p>
            <p className="text-gray-400">
              The Service Providers we use include:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-400">
              <li><span className="font-medium text-white">Supabase:</span> Database, authentication, and storage services. Their Privacy Policy can be viewed at: https://supabase.com/privacy</li>
              <li><span className="font-medium text-white">Vercel:</span> Hosting, analytics, and performance monitoring services. Their Privacy Policy can be viewed at: https://vercel.com/legal/privacy-policy</li>
              <li><span className="font-medium text-white">Stripe:</span> Payment processing services. Their Privacy Policy can be viewed at: https://stripe.com/us/privacy</li>
              <li><span className="font-medium text-white">Mailgun:</span> Email delivery services for contact form submissions. Their Privacy Policy can be viewed at: https://www.mailgun.com/legal/privacy-policy</li>
              <li><span className="font-medium text-white">Cloudflare:</span> CAPTCHA services (Turnstile) for spam prevention during account creation. Their Privacy Policy can be viewed at: https://www.cloudflare.com/privacypolicy</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-white">14. Analytics</h2>
            <p className="text-gray-400">
              We may use third-party Service Providers to monitor and analyze the use of our Service.
            </p>
            
            <div className="space-y-3 mt-3">
              <h3 className="text-lg font-medium text-white">Vercel Analytics</h3>
              <p className="text-gray-400">
                Vercel Analytics is a privacy-focused web analytics service offered by Vercel that tracks and reports website traffic. Vercel Analytics collects anonymous data without using cookies. It identifies users by a hash created from the incoming request, ensuring that individuals cannot be tracked across different websites or applications. The hash is reset daily, ensuring users cannot be tracked across different days.
              </p>
              <p className="text-gray-400">
                Data collected includes page views, referrer information, and user demographics like country and device type. This data is aggregated and does not allow for the reconstruction of individual browsing sessions.
              </p>
              <p className="text-gray-400">
                Currently, Vercel Analytics is active by default. We plan to implement an opt-in mechanism in the future to give users more control over analytics data collection.
              </p>
              <p className="text-gray-400">
                For more information on the privacy practices of Vercel, please visit the Vercel Privacy Policy web page: https://vercel.com/legal/privacy-policy
              </p>
            </div>

            <div className="space-y-3 mt-3">
              <h3 className="text-lg font-medium text-white">Vercel Speed Insights</h3>
              <p className="text-gray-400">
                Vercel Speed Insights provides performance metrics without associating data points with individual visitors or IP addresses. The collected data is anonymous and includes information such as route, URL, network speed, browser, device type, and country.
              </p>
              <p className="text-gray-400">
                For more information on the privacy practices of Vercel Speed Insights, please visit the Vercel Speed Insights Privacy Policy web page: https://vercel.com/docs/speed-insights/privacy-policy
              </p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-white">15. Payments</h2>
            <p className="text-gray-400">
              We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).
            </p>
            <p className="text-gray-400">
              We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
            </p>
            <p className="text-gray-400">
              The payment processors we work with are:
            </p>
            
            <div className="space-y-3 mt-3">
              <h3 className="text-lg font-medium text-white">Stripe</h3>
              <p className="text-gray-400">
                Their Privacy Policy can be viewed at: https://stripe.com/us/privacy
              </p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-white">16. Links to Other Sites</h2>
            <p className="text-gray-400">
              Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party&apos;s site. We strongly advise you to review the Privacy Policy of every site you visit.
            </p>
            <p className="text-gray-400">
              We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-white">17. Children&apos;s Privacy</h2>
            <p className="text-gray-400">
              Our Services are not intended for use by children under the age of 18 (&quot;Child&quot; or &quot;Children&quot;).
            </p>
            <p className="text-gray-400">
              We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-white">18. Changes to This Privacy Policy</h2>
            <p className="text-gray-400">
              We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
            </p>
            <p className="text-gray-400">
              We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update &quot;effective date&quot; at the top of this Privacy Policy.
            </p>
            <p className="text-gray-400">
              You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-white">19. Contact Us</h2>
            <p className="text-gray-400">
              If you have any questions about this Privacy Policy, please contact us by email: hello@bitbasis.
            </p>
          </section>

          <div className="mt-8 flex justify-center">
            <Button asChild variant="orange-outline" className="relative overflow-hidden bg-gradient-to-r from-bitcoin-orange to-[#D4A76A] text-white font-semibold shadow-lg hover:shadow-bitcoin-orange/30 transform hover:-translate-y-px transition-all duration-300 group">
              <Link href="/">
                <span className="relative z-10">Return to Home</span>
                <span className="absolute inset-0 bg-white opacity-0 group-hover:opacity-10 group-active:opacity-20 transition-opacity duration-300"></span>
              </Link>
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
} 