import {
  AlertCircle,
  ArrowDownRight,
  ArrowUpRight,
  Bitcoin,
  Check,
  ChevronLeft,
  ChevronRight,
  Circle,
  History,
  LayoutDashboard,
  LineChart,
  Loader2,
  LogOut,
  Menu,
  PanelLeft,
  PieChart,
  SendHorizontal,
  Settings,
  Upload,
  User,
  X,
  XCircle,
  type LucideIcon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Bitcoin,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  check: Check,
  circle: Circle,
  error: XCircle,
  warning: AlertCircle,
  menu: Menu,
  dashboard: LayoutDashboard,
  performance: LineChart,
  portfolio: PieChart,
  transactions: History,
  import: Upload,
  settings: Settings,
  user: User,
  logout: LogOut,
  panel: PanelLeft,
  arrowUp: ArrowUpRight,
  arrowDown: ArrowDownRight,
  send: SendHorizontal,
} as const 