-- Create the fear_greed_index table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.fear_greed_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    value INTEGER NOT NULL CHECK (value >= 0 AND value <= 100),
    classification VARCHAR(50) NOT NULL
);

-- Add RLS policy if not exists
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE schemaname = 'public' 
        AND tablename = 'fear_greed_index' 
        AND policyname = 'Allow authenticated users to read fear_greed_index'
    ) THEN
        ALTER TABLE public.fear_greed_index ENABLE ROW LEVEL SECURITY;

        -- Allow all authenticated users to read fear and greed index data
        CREATE POLICY "Allow authenticated users to read fear_greed_index"
            ON public.fear_greed_index
            FOR SELECT
            TO authenticated
            USING (true);

        -- Only allow service role to insert/update/delete
        CREATE POLICY "Only service role can modify fear_greed_index"
            ON public.fear_greed_index
            FOR ALL
            TO service_role
            USING (true)
            WITH CHECK (true);
    END IF;
END $$;

-- Add the date column if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'fear_greed_index' 
        AND column_name = 'date'
    ) THEN
        ALTER TABLE public.fear_greed_index
        ADD COLUMN date DATE;
    END IF;
END $$;

-- Add unique constraint if it doesn't exist (after ensuring column exists)
DO $$ 
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'fear_greed_index' 
        AND column_name = 'date'
    ) AND NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'fear_greed_index_date_key'
    ) THEN
        ALTER TABLE public.fear_greed_index
        ADD CONSTRAINT fear_greed_index_date_key UNIQUE (date);
    END IF;
END $$;
