-- Create new transfers table
CREATE TABLE IF NOT EXISTS "public"."transfers" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()),
    "user_id" uuid NOT NULL REFERENCES auth.users(id),
    "date" timestamp with time zone NOT NULL,
    "type" varchar(10) NOT NULL CHECK (type IN ('deposit', 'withdrawal')),
    "asset" varchar(10) NOT NULL DEFAULT 'BTC',
    "amount_btc" numeric(20,8) NOT NULL,
    "fee_amount_btc" numeric(20,8),
    "amount_fiat" numeric(20,8),
    "price" numeric(20,8),
    "hash" varchar(64),

    -- Constraints
    CONSTRAINT check_amounts_positive CHECK (
        amount_btc >= 0 AND
        COALESCE(fee_amount_btc, 0) >= 0 AND
        COALESCE(amount_fiat, 0) >= 0
    )
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_transfers_user_id ON public.transfers(user_id);
CREATE INDEX IF NOT EXISTS idx_transfers_date ON public.transfers(date);
CREATE INDEX IF NOT EXISTS idx_transfers_type ON public.transfers(type);

-- Add RLS policy
ALTER TABLE public.transfers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can only see their own transfers"
    ON public.transfers FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Add updated_at trigger
CREATE TRIGGER set_updated_at_transfers
    BEFORE UPDATE ON public.transfers
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- Add user_id validation trigger
CREATE TRIGGER ensure_user_id_matches_auth_transfers
    BEFORE INSERT OR UPDATE ON public.transfers
    FOR EACH ROW
    EXECUTE FUNCTION public.ensure_user_id_matches_auth();

COMMENT ON TABLE public.transfers IS 'Stores Bitcoin deposit and withdrawal transactions'; 