-- Create new unified transactions table
CREATE TABLE "public"."transactions" (
    -- Core fields
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()),
    "user_id" uuid NOT NULL REFERENCES auth.users(id),
    "date" timestamp with time zone NOT NULL,
    "type" varchar(10) NOT NULL CHECK (type IN ('buy', 'sell', 'deposit', 'withdrawal', 'interest')),
    "asset" varchar(10) NOT NULL DEFAULT 'BTC',
    
    -- Core transaction fields (matching spreadsheet headers)
    "sent_amount" numeric(20,8), -- Sent Amount
    "sent_currency" varchar(10), -- Sent Currency
    "sent_cost_basis" numeric(20,8), -- Sent Cost Basis
    "from_address" varchar(100), -- From
    "from_address_name" varchar(100), -- From Address
    "to_address" varchar(100), -- To
    "to_address_name" varchar(100), -- To Address
    "received_amount" numeric(20,8), -- Received Amount
    "received_currency" varchar(10), -- Received Currency
    "received_cost_basis" numeric(20,8), -- Received Cost Basis
    "fee_amount" numeric(20,8), -- Fee Amount
    "fee_currency" varchar(10), -- Fee Currency
    "fee_cost_basis" numeric(20,8), -- Fee Cost Basis
    "realized_return" numeric(20,8), -- Realized Return
    "fee_realized_return" numeric(20,8), -- Fee Realized Return
    "transaction_hash" varchar(70), -- Transaction Hash
    "comment" text, -- User comment/note about the transaction
    
    -- Additional fields for compatibility and functionality
    "price" numeric(20,8), -- BTC price at time of transaction
    "csv_upload_id" uuid NULL REFERENCES public.csv_uploads(id) ON DELETE CASCADE,
    
    -- Constraints
    CONSTRAINT check_amounts_positive CHECK (
        COALESCE(sent_amount, 0) >= 0 AND
        COALESCE(received_amount, 0) >= 0 AND
        COALESCE(fee_amount, 0) >= 0
    ),
    CONSTRAINT check_buy_fields CHECK (
        (type = 'buy' AND received_amount IS NOT NULL AND received_currency IS NOT NULL) OR
        type != 'buy'
    ),
    CONSTRAINT check_sell_fields CHECK (
        (type = 'sell' AND sent_amount IS NOT NULL AND sent_currency IS NOT NULL AND received_amount IS NOT NULL AND received_currency IS NOT NULL) OR
        type != 'sell'
    ),
    CONSTRAINT check_transfer_fields CHECK (
        ((type = 'deposit' OR type = 'withdrawal') AND 
         ((sent_amount IS NOT NULL AND sent_currency IS NOT NULL) OR 
          (received_amount IS NOT NULL AND received_currency IS NOT NULL))) OR
        (type != 'deposit' AND type != 'withdrawal')
    ),
    CONSTRAINT check_interest_fields CHECK (
        (type = 'interest' AND received_amount IS NOT NULL AND received_currency IS NOT NULL) OR
        type != 'interest'
    )
);

-- Create indexes for performance
CREATE INDEX idx_transactions_user_id ON public.transactions(user_id);
CREATE INDEX idx_transactions_date ON public.transactions(date);
CREATE INDEX idx_transactions_type ON public.transactions(type);
CREATE INDEX idx_transactions_user_date ON public.transactions(user_id, date);

-- Enable Row Level Security
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can view their own transactions" 
ON public.transactions 
FOR SELECT 
TO authenticated 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own transactions" 
ON public.transactions 
FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own transactions" 
ON public.transactions 
FOR UPDATE 
TO authenticated 
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own transactions" 
ON public.transactions 
FOR DELETE 
TO authenticated 
USING (auth.uid() = user_id);

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger for updated_at
CREATE TRIGGER update_transactions_updated_at 
    BEFORE UPDATE ON public.transactions 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Create function to get user transaction count for the new table
CREATE OR REPLACE FUNCTION public.get_user_transaction_count_v2(user_uuid uuid)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN (
        SELECT COUNT(*)::integer 
        FROM public.transactions 
        WHERE user_id = user_uuid
    );
END;
$$; 