-- Ensure price_update_logs table exists
CREATE TABLE IF NOT EXISTS public.price_update_logs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  started_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  service VARCHAR(50),
  status VARCHAR(50),
  message TEXT,
  success BOOLEAN DEFAULT true,
  error_message TEXT,
  response_status INTEGER,
  response_content TEXT
);

-- Ensure proper RLS policies for logs
ALTER TABLE public.price_update_logs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policy 
    WHERE polname = 'Allow authenticated users to read logs' 
    AND polrelid = 'public.price_update_logs'::regclass
  ) THEN
    CREATE POLICY "Allow authenticated users to read logs" 
    ON public.price_update_logs FOR SELECT 
    TO authenticated 
    USING (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policy 
    WHERE polname = 'Only service role can modify logs' 
    AND polrelid = 'public.price_update_logs'::regclass
  ) THEN
    CREATE POLICY "Only service role can modify logs" 
    ON public.price_update_logs
    TO service_role
    USING (true)
    WITH CHECK (true);
  END IF;
END $$;

-- Create a function to manage the cron schedule with proper permissions
CREATE OR REPLACE FUNCTION public.setup_btc_ath_schedule()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER -- Run as DB owner
AS $$
BEGIN
  -- First, remove any existing scheduled jobs for ATH checking
  DELETE FROM cron.job WHERE jobname LIKE '%btc-ath%';
  
  -- Add a consistent schedule
  PERFORM cron.schedule(
    'daily-btc-ath-check',       -- name of the cron job
    '0 0 * * *',                 -- schedule (midnight UTC daily)
    'SELECT public.check_and_update_btc_ath()'  -- SQL command to execute
  );
END;
$$;

-- Execute the schedule setup function
SELECT public.setup_btc_ath_schedule(); 