-- Ensure the ATH table exists with correct structure
CREATE TABLE IF NOT EXISTS public.ath (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  price_usd NUMERIC(20, 2) NOT NULL,
  ath_date TIMESTAMP WITH TIME ZONE NOT NULL,
  source VARCHAR(50) DEFAULT 'coinpaprika'
);

-- Ensure proper RLS policies
ALTER TABLE public.ath ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policy 
    WHERE polname = 'Allow authenticated users to read ATH' 
    AND polrelid = 'public.ath'::regclass
  ) THEN
    CREATE POLICY "Allow authenticated users to read ATH" 
    ON public.ath FOR SELECT 
    TO authenticated 
    USING (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policy 
    WHERE polname = 'Only service role can modify ATH' 
    AND polrelid = 'public.ath'::regclass
  ) THEN
    CREATE POLICY "Only service role can modify ATH" 
    ON public.ath
    TO service_role
    USING (true)
    WITH CHECK (true);
  END IF;
END $$;

-- Ensure price_update_logs table exists
CREATE TABLE IF NOT EXISTS public.price_update_logs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  started_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  service VARCHAR(50),
  status VARCHAR(50),
  message TEXT,
  success BOOLEAN DEFAULT true,
  error_message TEXT,
  response_status INTEGER,
  response_content TEXT
);

-- Ensure proper RLS policies for logs
ALTER TABLE public.price_update_logs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policy 
    WHERE polname = 'Allow authenticated users to read logs' 
    AND polrelid = 'public.price_update_logs'::regclass
  ) THEN
    CREATE POLICY "Allow authenticated users to read logs" 
    ON public.price_update_logs FOR SELECT 
    TO authenticated 
    USING (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policy 
    WHERE polname = 'Only service role can modify logs' 
    AND polrelid = 'public.price_update_logs'::regclass
  ) THEN
    CREATE POLICY "Only service role can modify logs" 
    ON public.price_update_logs
    TO service_role
    USING (true)
    WITH CHECK (true);
  END IF;
END $$; 