-- Create spot_price table for storing the latest BTC spot price
CREATE TABLE IF NOT EXISTS public.spot_price (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  price_usd NUMERIC(20, 2) NOT NULL,
  source VARCHAR(50) DEFAULT 'coinpaprika'
);

-- Create index on updated_at for efficient querying of recent prices
CREATE INDEX IF NOT EXISTS idx_spot_price_updated_at ON public.spot_price (updated_at);

-- Add RLS policies for spot_price
ALTER TABLE public.spot_price ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated users to read spot price data
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policy 
    WHERE polname = 'Allow authenticated users to read spot price' 
    AND polrelid = 'public.spot_price'::regclass
  ) THEN
    EXECUTE 'CREATE POLICY "Allow authenticated users to read spot price" 
    ON public.spot_price FOR SELECT 
    TO authenticated 
    USING (true)';
  END IF;
END $$;

-- Only service role can modify spot price data
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policy 
    WHERE polname = 'Only service role can modify spot price' 
    AND polrelid = 'public.spot_price'::regclass
  ) THEN
    EXECUTE 'CREATE POLICY "Only service role can modify spot price" 
    ON public.spot_price
    TO service_role
    USING (true)
    WITH CHECK (true)';
  END IF;
END $$;

-- Create ath (All Time High) table
CREATE TABLE IF NOT EXISTS public.ath (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  price_usd NUMERIC(20, 2) NOT NULL,
  ath_date TIMESTAMP WITH TIME ZONE NOT NULL,
  source VARCHAR(50) DEFAULT 'coinpaprika'
);

-- Add RLS policies for ath
ALTER TABLE public.ath ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated users to read ATH data
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policy 
    WHERE polname = 'Allow authenticated users to read ATH' 
    AND polrelid = 'public.ath'::regclass
  ) THEN
    EXECUTE 'CREATE POLICY "Allow authenticated users to read ATH" 
    ON public.ath FOR SELECT 
    TO authenticated 
    USING (true)';
  END IF;
END $$;

-- Only service role can modify ATH data
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policy 
    WHERE polname = 'Only service role can modify ATH' 
    AND polrelid = 'public.ath'::regclass
  ) THEN
    EXECUTE 'CREATE POLICY "Only service role can modify ATH" 
    ON public.ath
    TO service_role
    USING (true)
    WITH CHECK (true)';
  END IF;
END $$;

-- Create a function to update spot price with timestamp
CREATE OR REPLACE FUNCTION public.update_spot_price(
  new_price_usd NUMERIC(20, 2),
  source_name VARCHAR DEFAULT 'coinpaprika'
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.spot_price (price_usd, source, updated_at)
  VALUES (new_price_usd, source_name, timezone('utc'::text, now()));
  
  -- Keep only the most recent 100 records to prevent unbounded growth
  DELETE FROM public.spot_price
  WHERE id NOT IN (
    SELECT id FROM public.spot_price
    ORDER BY updated_at DESC
    LIMIT 100
  );
END;
$$;

-- Create a function to update ATH when a new one is detected
CREATE OR REPLACE FUNCTION public.update_ath(
  new_price_usd NUMERIC(20, 2),
  new_ath_date TIMESTAMP WITH TIME ZONE,
  source_name VARCHAR DEFAULT 'coinpaprika'
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  current_ath NUMERIC(20, 2);
BEGIN
  -- Get the current ATH if it exists
  SELECT price_usd INTO current_ath FROM public.ath
  ORDER BY price_usd DESC LIMIT 1;
  
  -- If no ATH exists or the new price is higher, update
  IF current_ath IS NULL OR new_price_usd > current_ath THEN
    INSERT INTO public.ath (price_usd, ath_date, source, updated_at)
    VALUES (new_price_usd, new_ath_date, source_name, timezone('utc'::text, now()));
  END IF;
END;
$$; 