-- Create new tables for orders, send, and receive transactions
CREATE TABLE IF NOT EXISTS "public"."orders" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()),
    "user_id" uuid NOT NULL REFERENCES auth.users(id),
    "date" timestamp with time zone NOT NULL,
    "type" varchar(4) NOT NULL CHECK (type IN ('buy', 'sell')),
    "asset" varchar(10) NOT NULL,
    "price" numeric(20,8) NOT NULL,
    "exchange" varchar(50),
    
    -- Buy fields
    "buy_fiat_amount" numeric(20,8),
    "buy_currency" varchar(10),
    "buy_btc_amount" numeric(20,8),
    "received_btc_amount" numeric(20,8),
    "received_currency" varchar(10),
    
    -- Sell fields
    "sell_btc_amount" numeric(20,8),
    "sell_btc_currency" varchar(10),
    "received_fiat_amount" numeric(20,8),
    "received_fiat_currency" varchar(10),
    
    -- Fee information
    "service_fee" numeric(20,8),
    "service_fee_currency" varchar(10),

    -- Constraints
    CONSTRAINT check_amounts_positive CHECK (
        COALESCE(buy_fiat_amount, 0) >= 0 AND
        COALESCE(buy_btc_amount, 0) >= 0 AND
        COALESCE(received_btc_amount, 0) >= 0 AND
        COALESCE(sell_btc_amount, 0) >= 0 AND
        COALESCE(received_fiat_amount, 0) >= 0 AND
        COALESCE(service_fee, 0) >= 0
    ),
    CONSTRAINT check_buy_fields CHECK (
        (type = 'buy' AND buy_fiat_amount IS NOT NULL AND buy_currency IS NOT NULL AND received_btc_amount IS NOT NULL) OR
        type != 'buy'
    ),
    CONSTRAINT check_sell_fields CHECK (
        (type = 'sell' AND sell_btc_amount IS NOT NULL AND received_fiat_amount IS NOT NULL AND received_fiat_currency IS NOT NULL) OR
        type != 'sell'
    )
);

CREATE TABLE IF NOT EXISTS "public"."send" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()),
    "user_id" uuid NOT NULL REFERENCES auth.users(id),
    "date" timestamp with time zone NOT NULL,
    "asset" varchar(10) NOT NULL,
    "type" varchar(4) NOT NULL DEFAULT 'send' CHECK (type = 'send'),
    
    -- Send fields
    "sent_amount" numeric(20,8) NOT NULL,
    "sent_currency" varchar(10) NOT NULL DEFAULT 'BTC' CHECK (sent_currency = 'BTC'),
    
    -- Fee information
    "network_fee" numeric(20,8),
    "network_fee_currency" varchar(10) DEFAULT 'BTC' CHECK (network_fee_currency = 'BTC'),

    -- Constraints
    CONSTRAINT check_amounts_positive CHECK (
        sent_amount >= 0 AND
        COALESCE(network_fee, 0) >= 0
    )
);

CREATE TABLE IF NOT EXISTS "public"."receive" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()),
    "user_id" uuid NOT NULL REFERENCES auth.users(id),
    "date" timestamp with time zone NOT NULL,
    "asset" varchar(10) NOT NULL,
    "type" varchar(7) NOT NULL DEFAULT 'receive' CHECK (type = 'receive'),
    "price" numeric(20,8) NOT NULL,
    "exchange" varchar(50),
    
    -- Receive fields
    "received_transfer_amount" numeric(20,8) NOT NULL,
    "received_currency" varchar(10) NOT NULL DEFAULT 'BTC' CHECK (received_currency = 'BTC'),

    -- Constraints
    CONSTRAINT check_amounts_positive CHECK (
        received_transfer_amount >= 0
    )
);

-- Create indexes for better query performance
CREATE INDEX idx_orders_user_id ON public.orders(user_id);
CREATE INDEX idx_orders_date ON public.orders(date);
CREATE INDEX idx_orders_type ON public.orders(type);
CREATE INDEX idx_orders_asset ON public.orders(asset);
CREATE INDEX idx_orders_exchange ON public.orders(exchange);

CREATE INDEX idx_send_user_id ON public.send(user_id);
CREATE INDEX idx_send_date ON public.send(date);
CREATE INDEX idx_send_asset ON public.send(asset);

CREATE INDEX idx_receive_user_id ON public.receive(user_id);
CREATE INDEX idx_receive_date ON public.receive(date);
CREATE INDEX idx_receive_asset ON public.receive(asset);
CREATE INDEX idx_receive_exchange ON public.receive(exchange);

-- Add triggers for updated_at
CREATE TRIGGER set_updated_at_orders
    BEFORE UPDATE ON public.orders
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER set_updated_at_send
    BEFORE UPDATE ON public.send
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER set_updated_at_receive
    BEFORE UPDATE ON public.receive
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- Add user_id validation triggers
CREATE TRIGGER ensure_user_id_matches_auth_orders
    BEFORE INSERT OR UPDATE ON public.orders
    FOR EACH ROW
    EXECUTE FUNCTION public.ensure_user_id_matches_auth();

CREATE TRIGGER ensure_user_id_matches_auth_send
    BEFORE INSERT OR UPDATE ON public.send
    FOR EACH ROW
    EXECUTE FUNCTION public.ensure_user_id_matches_auth();

CREATE TRIGGER ensure_user_id_matches_auth_receive
    BEFORE INSERT OR UPDATE ON public.receive
    FOR EACH ROW
    EXECUTE FUNCTION public.ensure_user_id_matches_auth();

-- Add RLS policies
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.send ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.receive ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can only see their own orders"
    ON public.orders FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can only see their own send transactions"
    ON public.send FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can only see their own receive transactions"
    ON public.receive FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Data migration (to be run after tables are created)
INSERT INTO public.orders (
    user_id, date, type, asset, price, exchange,
    buy_fiat_amount, buy_currency, received_btc_amount,
    sell_btc_amount, received_fiat_amount, received_fiat_currency,
    service_fee, service_fee_currency
)
SELECT 
    user_id, date,
    LOWER(type) as type,
    asset, price, exchange,
    CASE WHEN LOWER(type) = 'buy' THEN buy_amount ELSE NULL END as buy_fiat_amount,
    CASE WHEN LOWER(type) = 'buy' THEN buy_currency ELSE NULL END as buy_currency,
    CASE WHEN LOWER(type) = 'buy' THEN received_amount ELSE NULL END as received_btc_amount,
    CASE WHEN LOWER(type) = 'sell' THEN sent_amount ELSE NULL END as sell_btc_amount,
    CASE WHEN LOWER(type) = 'sell' THEN received_amount ELSE NULL END as received_fiat_amount,
    CASE WHEN LOWER(type) = 'sell' THEN received_currency ELSE NULL END as received_fiat_currency,
    service_fee, service_fee_currency
FROM public.transactions
WHERE LOWER(type) IN ('buy', 'sell');

INSERT INTO public.send (
    user_id, date, asset, sent_amount, network_fee, network_fee_currency
)
SELECT 
    user_id, date, asset,
    sent_amount,
    network_fee,
    network_currency
FROM public.transactions
WHERE LOWER(type) = 'send';

INSERT INTO public.receive (
    user_id, date, asset, price, exchange,
    received_transfer_amount
)
SELECT 
    user_id, date, asset, price, exchange,
    received_amount
FROM public.transactions
WHERE LOWER(type) = 'receive';

-- After successful migration, drop the old table
DROP TABLE public.transactions; 